// script.js — shared helpers used across all pages.
// Deliberately no framework: five pages, vanilla JS is easier to read
// top to bottom than explaining a build step to a recruiter.

const API = "/api";

async function apiPost(path, body) {
  const res = await fetch(API + path, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.detail || "Request failed");
  return data;
}

async function apiGet(path, token) {
  const res = await fetch(API + path, {
    headers: { Authorization: "Bearer " + token },
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.detail || "Request failed");
  return data;
}

function showError(el, message) {
  el.textContent = message;
  el.classList.add("show");
}

function hideError(el) {
  el.classList.remove("show");
}

// Wires a row of .otp-digit inputs so typing auto-advances, backspace
// moves back, and pasting a full code fills every box at once.
function wireOtpInputs(container, onComplete) {
  const digits = [...container.querySelectorAll(".otp-digit")];

  digits.forEach((input, i) => {
    input.addEventListener("input", () => {
      input.value = input.value.replace(/\D/g, "").slice(0, 1);
      if (input.value && i < digits.length - 1) digits[i + 1].focus();
      checkComplete();
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Backspace" && !input.value && i > 0) digits[i - 1].focus();
    });
    input.addEventListener("paste", (e) => {
      e.preventDefault();
      const text = (e.clipboardData.getData("text") || "").replace(/\D/g, "");
      digits.forEach((d, idx) => (d.value = text[idx] || ""));
      checkComplete();
    });
  });

  function checkComplete() {
    const code = digits.map((d) => d.value).join("");
    if (code.length === digits.length) onComplete(code);
  }

  digits[0].focus();
}

// Draws the 30-second TOTP refresh countdown. This is a real signal —
// codes generated by RFC 6238 rotate every 30s, so the ring tells the
// user exactly how much time is left to use the one on screen.
function startTotpCountdown(circleEl, labelEl) {
  const RADIUS = 6.5;
  const CIRCUMFERENCE = 2 * Math.PI * RADIUS;
  circleEl.style.strokeDasharray = CIRCUMFERENCE;

  function tick() {
    const secondsLeft = 30 - (Math.floor(Date.now() / 1000) % 30);
    const offset = CIRCUMFERENCE * (1 - secondsLeft / 30);
    circleEl.style.strokeDashoffset = offset;
    if (labelEl) labelEl.textContent = secondsLeft + "s";
  }
  tick();
  return setInterval(tick, 1000);
}
